'''
@Time : 2023-06-25 11:18
@Author : laolao
@FileName: 2.py
'''

import random

class CountryCodaTLD:
    AC = 'whois.nic.ac'
    AD = 'whois.ripe.net'
    AE = random.choice(['whois-check.aeda.net.ae', 'whois.aeda.net.ae'])
    AF = 'whois.nic.af'
    AG = 'whois.nic.ag'
    AI = random.choice(['whois.ai', 'whois.nic.ai'])
    AL = None
    AM = 'whois.amnic.net'
    AN = None
    AO = None
    AQ = None
    AR = 'whois.nic.ar'
    AS = 'whois.nic.as'
    AT = 'whois.nic.at'
    AU = random.choice(['whois.auda.org.au', 'whois.audns.net.au'])
    AW = 'whois.nic.aw'
    AX = 'whois.ax'
    AZ = None
    BA = None
    BB = None
    BD = None
    BE = 'whois.dns.be'
    BF = None
    BG = 'whois.register.bg'
    BH = None
    BI = 'whois1.nic.bi'
    BJ = 'whois.nic.bj'
    BL = None
    BM = None
    BN = 'whois.bnnic.bn'
    BO = 'whois.nic.bo'
    BQ = None
    BR = random.choice(['whois.nic.br', 'whois.registro.br'])
    BS = None
    BT = None
    BV = None
    BW = 'whois.nic.net.bw'
    BY = 'whois.cctld.by'
    BZ = 'whois.afilias-grs.info'
    CA = 'whois.cira.ca'
    CC = 'ccwhois.verisign-grs.com'
    CD = 'whois.nic.cd'
    CF = 'whois.dot.cf'
    CG = None
    CH = 'whois.nic.ch'
    CI = 'whois.nic.ci'
    CK = None
    CL = 'whois.nic.cl'
    CM = 'whois.netcom.cm'
    CN = 'whois.cnnic.cn'
    CO = 'whois.nic.co'
    CR = 'whois.nic.cr'
    CU = None
    CV = None
    CW = None
    CX = 'whois.nic.cx'
    CY = None
    CZ = 'whois.nic.cz'
    DE = 'whois.denic.de'
    DJ = None
    DK = 'whois.dk-hostmaster.dk'
    DM = 'whois.nic.dm'
    DO = 'whois.nic.do'
    DZ = 'whois.nic.dz'
    EC = 'whois.nic.ec'
    EE = random.choice(['whois.eenet.ee', 'whois.tld.ee'])
    EG = None
    EH = None
    ER = None
    ES = 'whois.nic.es'
    ET = None
    EU = 'whois.eu'
    FI = 'whois.fi'
    FJ = 'whois.usp.ac.fj'
    FK = None
    FM = 'whois.nic.fm'
    FO = 'whois.nic.fo'
    FR = 'whois.nic.fr'
    GA = 'GA.whois-servers.net'
    GB = None
    GD = 'whois.nic.gd'
    GE = 'whois.nic.ge'
    GF = 'whois.mediaserv.net'
    GG = random.choice(['whois.gg', 'whois.channelisles.net'])
    GH = None
    GI = random.choice(['whois2.afilias-grs.net', 'whois.afilias-grs.info'])
    GL = 'whois.nic.gl'
    GM = None
    GN = None
    GP = 'whois.nic.gp'
    GQ = 'whois.dominio.gq'
    GR = None
    GS = random.choice(['whois.nic.gs', 'whois.adamsnames.tc'])
    GT = None
    GU = None
    GW = None
    GY = 'whois.registry.gy'
    HK = 'whois.hkirc.hk'
    HM = 'whois.registry.hm'
    HN = 'whois.nic.hn'
    HR = 'whois.dns.hr'
    HT = 'whois.nic.ht'
    HU = 'whois.nic.hu'
    ID = random.choice(['whois.pandi.or.id', 'whois.id'])
    IE = random.choice(['whois.domainregistry.ie', 'whois.weare.ie'])
    IL = 'whois.isoc.org.il'
    IM = 'whois.nic.im'
    IN = random.choice(['whois.inregistry.in', 'whois.registry.in'])
    IO = 'whois.nic.io'
    IQ = 'whois.cmc.iq'
    IR = 'whois.nic.ir'
    IS = 'whois.isnic.is'
    IT = 'whois.nic.it'
    JE = random.choice(['whois.channelisles.net', 'whois.je'])
    JM = None
    JO = None
    JP = 'whois.jprs.jp'
    KE = 'whois.kenic.or.ke'
    KG = 'whois.kg'
    KH = None
    KI = 'whois.nic.ki'
    KM = None
    KN = 'whois.nic.kn'
    KP = None
    KR = 'whois.kr'
    KW = None
    KY = 'whois.kyregistry.ky'
    KZ = 'whois.nic.kz'
    LA = 'whois.nic.la'
    LB = None
    LC = 'whois.afilias-grs.info'
    LI = 'whois.nic.li'
    LK = None
    LR = None
    LS = 'whois.nic.ls'
    LT = 'whois.domreg.lt'
    LU = 'whois.dns.lu'
    LV = 'whois.nic.lv'
    LY = 'whois.nic.ly'
    MA = random.choice(['whois.iam.net.ma', 'whois.registre.ma'])
    MC = None
    MD = 'whois.nic.md'
    ME = 'whois.nic.me'
    MF = None
    MG = 'whois.nic.mg'
    MH = None
    MK = 'whois.marnet.mk'
    ML = 'whois.dot.ml'
    MM = 'whois.registry.gov.mm'
    MN = random.choice(['whois.afilias-grs.info', 'whois.nic.mn'])
    MO = 'whois.monic.mo'
    MP = 'whois.nic.mp'
    MQ = 'whois.mediaserv.net'
    MR = 'whois.nic.mr'
    MS = random.choice(['whois.nic.ms', 'whois.adamsnames.tc'])
    MT = None
    MU = 'whois.nic.mu'
    MV = None
    MW = 'whois.nic.mw'
    MX = 'whois.mx'
    MY = 'whois.mynic.my'
    MZ = 'whois.nic.mz'
    NA = 'whois.na-nic.com.na'
    NC = 'whois.nc'
    NE = None
    NF = 'whois.nic.nf'
    NG = 'whois.nic.net.ng'
    NI = None
    NL = 'whois.domain-registry.nl'
    NO = 'whois.norid.no'
    NP = None
    NR = None
    NU = 'whois.iis.nu'
    NZ = 'whois.srs.net.nz'
    OM = 'whois.registry.om'
    PA = None
    PE = 'kero.yachay.pe'
    PF = 'whois.registry.pf'
    PG = None
    PH = None
    PK = None
    PL = 'whois.dns.pl'
    PM = random.choice(['whois.nic.fr', 'whois.nic.pm'])
    PN = None
    PR = random.choice(['whois.nic.pr', 'whois.afilias-srs.net'])
    PS = 'whois.pnina.ps'
    PT = 'whois.dns.pt'
    PW = 'whois.nic.pw'
    PY = None
    QA = 'whois.registry.qa'
    RE = random.choice(['whois.nic.fr', 'whois.nic.re'])
    RO = 'whois.rotld.ro'
    RS = 'whois.rnids.rs'
    RU = random.choice(['whois.tcinet.ru', 'whois.ripn.net'])
    RW = 'whois.ricta.org.rw'
    SA = 'whois.nic.net.sa'
    SB = 'whois.nic.net.sb'
    SC = random.choice(['whois2.afilias-grs.net', 'whois.afilias-grs.info'])
    SD = None
    SE = 'whois.iis.se'
    SG = random.choice(['whois.sgnic.sg', 'whois.nic.net.sg'])
    SH = 'whois.nic.sh'
    SI = random.choice(['whois.register.si', 'whois.arnes.si'])
    SJ = None
    SK = 'whois.sk-nic.sk'
    SL = 'whois.nic.sl'
    SM = 'whois.nic.sm'
    SN = 'whois.nic.sn'
    SO = 'whois.nic.so'
    SR = None
    SS = 'whois.nic.ss'
    ST = 'whois.nic.st'
    SU = random.choice(['whois.tcinet.ru', 'whois.ripn.net'])
    SV = None
    SX = 'whois.sx'
    SY = 'whois.tld.sy'
    SZ = None
    TC = random.choice(['whois.nic.tc', 'whois.adamsnames.tc'])
    TD = 'whois.nic.td'
    TF = random.choice(['whois.nic.tf', 'whois.adamsnames.tc'])
    TG = 'whois.nic.tg'
    TH = 'whois.thnic.co.th'
    TJ = None
    TK = 'whois.dot.tk'
    TL = 'whois.nic.tl'
    TM = 'whois.nic.tm'
    TN = 'whois.ati.tn'
    TO = random.choice(['whois.tonic.to', 'monarch.tonic.to'])
    TP = None
    TR = 'whois.nic.tr'
    TT = None
    TV = random.choice(['tvwhois.verisign-grs.com', 'whois.nic.tv'])
    TW = 'whois.twnic.net.tw'
    TZ = 'whois.tznic.or.tz'
    UA = 'whois.ua'
    UG = 'whois.co.ug'
    UK = 'whois.nic.uk'
    UM = None
    US = 'whois.nic.us'
    UY = 'whois.nic.org.uy'
    UZ = 'whois.cctld.uz'
    VA = None
    VC = random.choice(['whois2.afilias-grs.net', 'whois.adamsnames.tc'])
    VE = 'whois.nic.ve'
    VG = random.choice(['whois.nic.vg', 'ccwhois.ksregistry.net'])
    VI = None
    VN = None
    VU = random.choice(['vunic.vu', 'whois.dnrs.neustar'])
    WF = random.choice(['whois.nic.wf', 'whois.nic.fr'])
    WS = 'whois.website.ws'
    XN__2SCRJ9C = 'whois.registry.in'
    XN__3E0B707E = 'whois.kr'
    XN__3HCRJ9C = 'whois.registry.in'
    XN__45BR5CYL = 'whois.registry.in'
    XN__45BRJ9C = 'whois.registry.in'
    XN__54B7FTA0CC = None
    XN__80AO21A = 'whois.nic.kz'
    XN__90A3AC = 'whois.rnids.rs'
    XN__90AE = 'whois.imena.bg'
    XN__90AIS = 'whois.cctld.by'
    XN__CLCHC0EA0B2G2A9GCD = 'whois.sgnic.sg'
    XN__D1ALF = 'whois.marnet.mk'
    XN__E1A4C = 'whois.eu'
    XN__FIQS8S = 'cwhois.cnnic.cn'
    XN__FIQZ9S = 'cwhois.cnnic.cn'
    XN__FPCRJ9C3D = 'whois.registry.in'
    XN__FZC2C9E2C = None
    XN__GECRJ9C = 'whois.registry.in'
    XN__H2BREG3EVE = 'whois.registry.in'
    XN__H2BRJ9C = 'whois.registry.in'
    XN__H2BRJ9C8C = 'whois.registry.in'
    XN__J1AMH = 'whois.dotukr.com'
    XN__J6W193G = 'whois.hkirc.hk'
    XN__KPRW13D = 'whois.twnic.net.tw'
    XN__KPRY57D = 'whois.twnic.net.tw'
    XN__L1ACC = None
    XN__LGBBAT1AD8J = 'whois.nic.dz'
    XN__MGB9AWBF = 'whois.registry.om'
    XN__MGBA3A4F16A = 'whois.nic.ir'
    XN__MGBAAM7A8H = 'whois.aeda.net.ae'
    XN__MGBAI9AZGQP6J = None
    XN__MGBAYH7GPA = None
    XN__MGBBH1A = 'whois.registry.in'
    XN__MGBBH1A71E = 'whois.registry.in'
    XN__MGBC0A9AZCG = None
    XN__MGBERP4A5D4AR = 'whois.nic.net.sa'
    XN__MGBGU82A = 'whois.registry.in'
    XN__MGBPL2FH = None
    XN__MGBTX2B = 'whois.cmc.iq'
    XN__MGBX4CD0AB = 'whois.mynic.my'
    XN__MIX891F = 'whois.monic.mo'
    XN__NODE = 'whois.itdc.ge'
    XN__O3CW4H = 'whois.thnic.co.th'
    XN__OGBPF8FL = 'whois.tld.sy'
    XN__P1AI = 'whois.tcinet.ru'
    XN__PGBS0DH = 'whois.ati.tn'
    XN__QXAM = None
    XN__RVC1E0AM3E = 'whois.registry.in'
    XN__S9BRJ9C = 'whois.registry.in'
    XN__WGBH1C = None
    XN__WGBL6A = 'whois.registry.qa'
    XN__XKC2AL3HYE2A = None
    XN__XKC2DL3A5EE0H = 'whois.registry.in'
    XN__Y9A3AQ = 'whois.amnic.net'
    XN__YFRO4I67O = 'whois.sgnic.sg'
    XN__YGBI2AMMX = 'whois.pnina.ps'
    YE = None
    YT = random.choice(['whois.nic.yt', 'whois.nic.fr'])
    ZA = None
    ZM = random.choice(['whois.zicta.zm', 'whois.nic.zm'])
    ZW = None

class SponsoredTLD:
    AERO = 'whois.aero'
    ASIA = 'whois.nic.asia'
    CAT = random.choice(['whois.nic.cat', 'whois.cat'])
    COOP = 'whois.nic.coop'
    EDU = 'whois.educause.edu'
    GOV = 'whois.dotgov.gov'
    INT = 'whois.iana.org'
    JOBS = 'whois.nic.jobs'
    MIL = 'whois.internic.net'
    MOBI = random.choice(['whois.afilias.net', 'whois.nic.mobi'])
    MUSEUM = random.choice(['whois.nic.museum', 'whois.museum'])
    POST = 'whois.dotpostregistry.net'
    TEL = 'whois.nic.tel'
    TRAVEL = 'whois.nic.travel'
    XXX = random.choice(['whois.nic.xxx', 'whois.registrar.adult'])

class GenericTLD:
    AAA = None
    AARP = 'whois.nic.aarp'
    ABARTH = 'whois.afilias-srs.net'
    ABB = None
    ABBOTT = 'whois.afilias-srs.net'
    ABBVIE = 'whois.afilias-srs.net'
    ABC = 'whois.nic.abc'
    ABLE = None
    ABOGADO = random.choice(['whois.nic.abogado', 'whois-dub.mm-registry.com'])
    ABUDHABI = 'whois.nic.abudhabi'
    ACADEMY = random.choice(['whois.donuts.co', 'whois.nic.academy'])
    ACCENTURE = None
    ACCOUNTANT = 'whois.nic.accountant'
    ACCOUNTANTS = random.choice(['whois.nic.accountants', 'whois.donuts.co'])
    ACO = random.choice(['whois.afilias-srs.net', 'whois.nic.aco'])
    ACTIVE = 'whois.afilias-srs.net'
    ACTOR = random.choice(['whois.unitedtld.com', 'whois.nic.actor'])
    ADAC = 'whois.nic.adac'
    ADS = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    ADULT = random.choice(['whois.registrar.adult', 'whois.afilias-srs.net'])
    AEG = 'whois.nic.aeg'
    AETNA = None
    AFAMILYCOMPANY = 'whois.nic.afamilycompany'
    AFL = 'whois.nic.afl'
    AFRICA = 'africa-whois.registry.net.za'
    AGAKHAN = 'whois.afilias-srs.net'
    AGENCY = random.choice(['whois.nic.agency', 'whois.donuts.co'])
    AIG = None
    AIGO = 'whois.afilias-srs.net'
    AIRBUS = 'whois.nic.airbus'
    AIRFORCE = random.choice(['whois.unitedtld.com', 'whois.nic.airforce'])
    AIRTEL = 'whois.nic.airtel'
    AKDN = 'whois.afilias-srs.net'
    ALFAROMEO = 'whois.afilias-srs.net'
    ALIBABA = random.choice(['whois.nic.alibaba', 'whois.afilias-srs.net'])
    ALIPAY = random.choice(['whois.afilias-srs.net', 'whois.nic.alipay'])
    ALLFINANZ = random.choice(['whois.ksregistry.net', 'whois.nic.allfinanz'])
    ALLSTATE = 'whois.afilias-srs.net'
    ALLY = random.choice(['whois.nic.ally', 'whois.afilias-srs.net'])
    ALSACE = 'whois-alsace.nic.fr'
    ALSTOM = 'whois.nic.alstom'
    AMERICANEXPRESS = None
    AMERICANFAMILY = 'whois.nic.americanfamily'
    AMEX = None
    AMFAM = 'whois.nic.amfam'
    AMICA = None
    AMSTERDAM = 'whois.nic.amsterdam'
    ANALYTICS = None
    ANDROID = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    ANQUAN = 'whois.teleinfo.cn'
    ANZ = 'whois.nic.anz'
    AOL = 'whois.nic.aol'
    APARTMENTS = random.choice(['whois.donuts.co', 'whois.nic.apartments'])
    APP = 'whois.nic.google'
    APPLE = 'whois.afilias-srs.net'
    AQUARELLE = random.choice(['whois-aquarelle.nic.fr', 'whois.nic.aquarelle'])
    ARAMCO = None
    ARCHI = random.choice(['whois.ksregistry.net', 'whois.afilias.net'])
    ARMY = random.choice(['whois.nic.army', 'whois.rightside.co'])
    ART = random.choice(['whois.nic.art', 'whois.centralnic.com'])
    ARTE = 'whois.nic.arte'
    ASDA = 'whois.nic.asda'
    ASSOCIATES = random.choice(['whois.nic.associates', 'whois.donuts.co'])
    ATHLETA = None
    ATTORNEY = random.choice(['whois.nic.attorney', 'whois.rightside.co'])
    AUCTION = random.choice(['whois.nic.auction', 'whois.donuts.co'])
    AUDI = 'whois.afilias-srs.net'
    AUDIBLE = 'whois.nic.audible'
    AUDIO = 'whois.uniregistry.net'
    AUSPOST = 'whois.nic.auspost'
    AUTHOR = 'whois.nic.author'
    AUTO = random.choice(['whois.uniregistry.net', 'whois.nic.auto'])
    AUTOS = 'whois.afilias-srs.net'
    AVIANCA = 'whois.afilias-srs.net'
    AWS = 'whois.nic.aws'
    AXA = None
    AZURE = None
    BABY = 'whois.nic.baby'
    BAIDU = random.choice(['whois.ngtld.cn', 'whois.gtld.knet.cn'])
    BANAMEX = None
    BANANAREPUBLIC = None
    BAND = random.choice(['whois.rightside.co', 'whois.nic.band'])
    BANK = 'whois.nic.bank'
    BAR = 'whois.nic.bar'
    BARCELONA = 'whois.nic.barcelona'
    BARCLAYCARD = 'whois.nic.barclaycard'
    BARCLAYS = 'whois.nic.barclays'
    BAREFOOT = 'whois.nic.barefoot'
    BARGAINS = random.choice(['whois.nic.bargains', 'whois.donuts.co'])
    BASEBALL = None
    BASKETBALL = 'whois.nic.basketball'
    BAUHAUS = 'whois.nic.bauhaus'
    BAYERN = random.choice(['whois.nic.bayern', 'whois-dub.mm-registry.com'])
    BBC = 'whois.nic.bbc'
    BBT = 'whois.nic.bbt'
    BBVA = 'whois.nic.bbva'
    BCG = random.choice(['whois.afilias-srs.net', 'whois.nic.bcg'])
    BCN = 'whois.nic.bcn'
    BEATS = 'whois.afilias-srs.net'
    BEAUTY = 'whois.nic.beauty'
    BEER = random.choice(['whois.nic.beer', 'whois-dub.mm-registry.com'])
    BENTLEY = 'whois.nic.bentley'
    BERLIN = 'whois.nic.berlin'
    BEST = 'whois.nic.best'
    BESTBUY = random.choice(['whois.nic.bestbuy', 'whois.afilias-srs.net'])
    BET = 'whois.afilias.net'
    BHARTI = None
    BIBLE = 'whois.nic.bible'
    BID = 'whois.nic.bid'
    BIKE = random.choice(['whois.donuts.co', 'whois.nic.bike'])
    BING = None
    BINGO = random.choice(['whois.nic.bingo', 'whois.donuts.co'])
    BIO = random.choice(['whois.ksregistry.net', 'whois.afilias.net'])
    BIZ = random.choice(['whois.biz', 'whois.nic.biz'])
    BLACK = 'whois.afilias.net'
    BLACKFRIDAY = 'whois.uniregistry.net'
    BLANCO = 'whois.nic.blanco'
    BLOCKBUSTER = random.choice(['whois.nic.blockbuster', 'whois.afilias-srs.net'])
    BLOG = 'whois.nic.blog'
    BLOOMBERG = None
    BLUE = 'whois.afilias.net'
    BMS = 'whois.nic.bms'
    BMW = random.choice(['whois.ksregistry.net', 'whois.nic.bmw'])
    BNL = 'whois.afilias-srs.net'
    BNPPARIBAS = 'whois.afilias-srs.net'
    BOATS = 'whois.afilias-srs.net'
    BOEHRINGER = 'whois.afilias-srs.net'
    BOFA = 'whois.nic.bofa'
    BOM = 'whois.gtlds.nic.br'
    BOND = 'whois.nic.bond'
    BOO = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    BOOK = 'whois.nic.book'
    BOOKING = None
    BOOTS = 'whois.nic.boots'
    BOSCH = 'whois.nic.bosch'
    BOSTIK = random.choice(['whois.nic.bostik', 'whois-bostik.nic.fr'])
    BOSTON = 'whois.nic.boston'
    BOT = 'whois.nic.bot'
    BOUTIQUE = random.choice(['whois.nic.boutique', 'whois.donuts.co'])
    BOX = 'whois.nic.box'
    BRADESCO = random.choice(['whois-cl01.mm-registry.com', 'whois.nic.bradesco'])
    BRIDGESTONE = 'whois.nic.bridgestone'
    BROADWAY = random.choice(['whois-cl01.mm-registry.com', 'whois.nic.broadway'])
    BROKER = 'whois.nic.broker'
    BROTHER = 'whois.nic.brother'
    BRUSSELS = 'whois.nic.brussels'
    BUDAPEST = random.choice(['whois.nic.budapest', 'whois-dub.mm-registry.com'])
    BUGATTI = 'whois.afilias-srs.net'
    BUILD = 'whois.nic.build'
    BUILDERS = random.choice(['whois.donuts.co', 'whois.nic.builders'])
    BUSINESS = random.choice(['whois.donuts.co', 'whois.nic.business'])
    BUY = random.choice(['whois.afilias-srs.net', 'whois.nic.buy'])
    BUZZ = 'whois.nic.buzz'
    BZH = random.choice(['whois.nic.bzh', 'whois-bzh.nic.fr'])
    CAB = random.choice(['whois.nic.cab', 'whois.donuts.co'])
    CAFE = random.choice(['whois.donuts.co', 'whois.nic.cafe'])
    CAL = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    CALL = 'whois.nic.call'
    CALVINKLEIN = None
    CAM = random.choice(['whois.ksregistry.net', 'whois.nic.cam'])
    CAMERA = random.choice(['whois.donuts.co', 'whois.nic.camera'])
    CAMP = random.choice(['whois.donuts.co', 'whois.nic.camp'])
    CANCERRESEARCH = 'whois.nic.cancerresearch'
    CANON = 'whois.nic.canon'
    CAPETOWN = 'capetown-whois.registry.net.za'
    CAPITAL = random.choice(['whois.donuts.co', 'whois.nic.capital'])
    CAPITALONE = 'whois.nic.capitalone'
    CAR = random.choice(['whois.nic.car', 'whois.uniregistry.net'])
    CARAVAN = None
    CARDS = random.choice(['whois.donuts.co', 'whois.nic.cards'])
    CARE = random.choice(['whois.donuts.co', 'whois.nic.care'])
    CAREER = 'whois.nic.career'
    CAREERS = random.choice(['whois.nic.careers', 'whois.donuts.co'])
    CARS = random.choice(['whois.nic.cars', 'whois.uniregistry.net'])
    CARTIER = None
    CASA = random.choice(['whois.nic.casa', 'whois-dub.mm-registry.com'])
    CASE = random.choice(['whois.nic.case', 'whois.afilias-srs.net'])
    CASEIH ='whois.afilias-srs.net'
    CASH = random.choice(['whois.nic.cash', 'whois.donuts.co'])
    CASINO = random.choice(['whois.donuts.co', 'whois.nic.casino'])
    CATERING = random.choice(['whois.donuts.co', 'whois.nic.catering'])
    CATHOLIC = 'whois.nic.catholic'
    CBA = 'whois.nic.cba'
    CBN = None
    CBRE = None
    CBS = 'whois.afilias-srs.net'
    CEB ='whois.afilias-srs.net'
    CENTER = random.choice(['whois.donuts.co', 'whois.nic.center'])
    CEO = 'whois.nic.ceo'
    CERN = 'whois.afilias-srs.net'
    CFA = 'whois.nic.cfa'
    CFD = 'whois.nic.cfd'
    CHANEL = 'whois.nic.chanel'
    CHANNEL = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    CHASE = None
    CHAT = random.choice(['whois.nic.chat', 'whois.donuts.co'])
    CHEAP = random.choice(['whois.donuts.co', 'whois.nic.cheap'])
    CHINTAI = 'whois.nic.chintai'
    CHLOE = None
    CHRISTMAS = 'whois.uniregistry.net'
    CHROME = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    CHRYSLER = 'whois.afilias-srs.net'
    CHURCH = random.choice(['whois.donuts.co', 'whois.nic.church'])
    CIPRIANI = 'whois.afilias-srs.net'
    CIRCLE = 'whois.nic.circle'
    CISCO = None
    CITADEL = None
    CITI = None
    CITIC = None
    CITY = random.choice(['whois.nic.city', 'whois.donuts.co'])
    CITYEATS = 'whois.nic.cityeats'
    CLAIMS = random.choice(['whois.nic.claims', 'whois.donuts.co'])
    CLEANING = random.choice(['whois.nic.cleaning', 'whois.donuts.co'])
    CLICK = 'whois.uniregistry.net'
    CLINIC = random.choice(['whois.nic.clinic', 'whois.donuts.co'])
    CLINIQUE = random.choice(['whois.afilias-srs.net', 'whois.nic.clinique'])
    CLOTHING = random.choice(['whois.donuts.co', 'whois.nic.clothing'])
    CLOUD = 'whois.nic.cloud'
    CLUB = 'whois.nic.club'
    CLUBMED = 'whois.nic.clubmed'
    COACH = random.choice(['whois.donuts.co', 'whois.nic.coach'])
    CODES = random.choice(['whois.donuts.co', 'whois.nic.codes'])
    COFFEE = random.choice(['whois.donuts.co', 'whois.nic.coffee'])
    COLLEGE = random.choice(['whois.nic.college', 'whois.centralnic.com'])
    COLOGNE = random.choice(['whois-fe1.pdt.cologne.tango.knipp.de', 'whois.ryce-rsp.com'])
    COM = random.choice(['whois.verisign-grs.com', 'whois.crsnic.net'])
    COMCAST = 'whois.nic.comcast'
    COMMBANK = 'whois.nic.commbank'
    COMMUNITY = random.choice(['whois.nic.community', 'whois.donuts.co'])
    COMPANY = random.choice(['whois.nic.company', 'whois.donuts.co'])
    COMPARE = 'whois.nic.compare'
    COMPUTER = random.choice(['whois.nic.computer', 'whois.donuts.co'])
    COMSEC = 'whois.nic.comsec'
    CONDOS = random.choice(['whois.nic.condos', 'whois.donuts.co'])
    CONSTRUCTION = random.choice(['whois.donuts.co', 'whois.nic.construction'])
    CONSULTING = random.choice(['whois.nic.consulting', 'whois.unitedtld.com'])
    CONTACT = 'whois.nic.contact'
    CONTRACTORS = random.choice(['whois.donuts.co', 'whois.nic.contractors'])
    COOKING = random.choice(['whois.nic.cooking', 'whois-dub.mm-registry.com'])
    COOKINGCHANNEL = 'whois.nic.cookingchannel'
    COOL = random.choice(['whois.nic.cool', 'whois.donuts.co'])
    CORSICA = 'whois-corsica.nic.fr'
    COUNTRY = random.choice(['whois.uniregistry.net', 'whois-dub.mm-registry.com'])
    COUPON = None
    COUPONS = random.choice(['whois.nic.coupons', 'whois.donuts.co'])
    COURSES = random.choice(['whois.aridnrs.net.au', 'whois.nic.courses'])
    CPA = 'whois.nic.cpa'
    CREDIT = random.choice(['whois.donuts.co', 'whois.nic.credit'])
    CREDITCARD = random.choice(['whois.nic.creditcard', 'whois.donuts.co'])
    CREDITUNION = 'whois.afilias-srs.net'
    CRICKET = 'whois.nic.cricket'
    CROWN = None
    CRS = None
    CRUISE = 'whois.nic.cruise'
    CRUISES = random.choice(['whois.nic.cruises', 'whois.donuts.co'])
    CSC = 'whois.nic.csc'
    CUISINELLA = 'whois.nic.cuisinella'
    CYMRU = 'whois.nic.cymru'
    CYOU = random.choice(['whois.afilias-srs.net', 'whois.nic.cyou'])
    DABUR = 'whois.afilias-srs.net'
    DAD = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    DANCE = random.choice(['whois.unitedtld.com', 'whois.nic.dance'])
    DATA = 'whois.nic.data'
    DATE = 'whois.nic.date'
    DATING = random.choice(['whois.donuts.co', 'whois.nic.dating'])
    DATSUN = 'whois.nic.gmo'
    DAY = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    DCLK = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    DDS = random.choice(['whois.nic.dds', 'whois-dub.mm-registry.com'])
    DEAL = 'whois.nic.deal'
    DEALER = 'whois.nic.dealer'
    DEALS = random.choice(['whois.nic.deals', 'whois.donuts.co'])
    DEGREE = random.choice(['whois.nic.degree', 'whois.rightside.co'])
    DELIVERY = random.choice(['whois.nic.delivery', 'whois.donuts.co'])
    DELL = None
    DELOITTE = 'whois.nic.deloitte'
    DELTA = random.choice(['whois.afilias-srs.net', 'whois.nic.delta'])
    DEMOCRAT = random.choice(['whois.nic.democrat', 'whois.unitedtld.com'])
    DENTAL = random.choice(['whois.nic.dental', 'whois.donuts.co'])
    DENTIST = random.choice(['whois.rightside.co', 'whois.nic.dentist'])
    DESI = random.choice(['whois.ksregistry.net', 'whois.nic.desi'])
    DESIGN = 'whois.nic.design'
    DEV = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    DHL = None
    DIAMONDS = random.choice(['whois.nic.diamonds', 'whois.donuts.co'])
    DIET = 'whois.uniregistry.net'
    DIGITAL = random.choice(['whois.donuts.co', 'whois.nic.digital'])
    DIRECT = random.choice(['whois.donuts.co', 'whois.nic.direct'])
    DIRECTORY = random.choice(['whois.donuts.co', 'whois.nic.directory'])
    DISCOUNT = random.choice(['whois.nic.discount', 'whois.donuts.co'])
    DISCOVER = None
    DISH = random.choice(['whois.nic.dish', 'whois.afilias-srs.net'])
    DIY = 'whois.nic.diy'
    DNP = 'whois.nic.dnp'
    DOCS = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    DOCTOR = random.choice(['whois.donuts.co', 'whois.nic.doctor'])
    DODGE = 'whois.afilias-srs.net'
    DOG = random.choice(['whois.nic.dog', 'whois.donuts.co'])
    DOHA = 'whois.nic.doha'
    DOMAINS = random.choice(['whois.donuts.co', 'whois.nic.domains'])
    DOOSAN = 'whois.nic.xn--cg4bki'
    DOT = random.choice(['whois.nic.dot', 'whois.afilias-srs.net'])
    DOWNLOAD = 'whois.nic.download'
    DRIVE = 'whois.nic.google'
    DTV = random.choice(['whois.afilias-srs.net', 'whois.nic.dtv'])
    DUBAI = 'whois.nic.dubai'
    DUCK = 'whois.nic.duck'
    DUNLOP = random.choice(['whois.afilias-srs.net', 'whois.nic.dunlop'])
    DUNS = None
    DUPONT = None
    DURBAN = 'durban-whois.registry.net.za'
    DVAG = random.choice(['whois.ksregistry.net', 'whois.nic.dvag'])
    DVR = random.choice(['whois.afilias-srs.net', 'whois.nic.dvr'])
    EARTH = 'whois.nic.earth'
    EAT = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    ECO = random.choice(['whois.nic.eco', 'whois.afilias-srs.net'])
    EDEKA = 'whois.afilias-srs.net'
    EDUCATION = random.choice(['whois.donuts.co', 'whois.nic.education'])
    EMAIL = random.choice(['whois.donuts.co', 'whois.nic.email'])
    EMERCK = 'whois.afilias-srs.net'
    ENERGY = random.choice(['whois.nic.energy', 'whois.donuts.co'])
    ENGINEER = random.choice(['whois.nic.engineer', 'whois.rightside.co'])
    ENGINEERING = random.choice(['whois.donuts.co', 'whois.nic.engineering'])
    ENTERPRISES = random.choice(['whois.donuts.co', 'whois.nic.enterprises'])
    EPOST = None
    EPSON = random.choice(['whois.nic.epson', 'whois.aridnrs.net.au'])
    EQUIPMENT = random.choice(['whois.nic.equipment', 'whois.donuts.co'])
    ERICSSON = 'whois.nic.ericsson'
    ERNI = 'whois.nic.erni'
    ESQ = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    ESTATE = random.choice(['whois.donuts.co', 'whois.nic.estate'])
    ESURANCE = 'whois.afilias-srs.net'
    ETISALAT = 'whois.centralnic.com'
    EUROVISION = 'whois.nic.eurovision'
    EUS = random.choice(['whois.eus.coreregistry.net', 'whois.nic.eus'])
    EVENTS = random.choice(['whois.nic.events', 'whois.donuts.co'])
    EVERBANK ='whois.nic.everbank'
    EXCHANGE = random.choice(['whois.donuts.co', 'whois.nic.exchange'])
    EXPERT = random.choice(['whois.nic.expert', 'whois.donuts.co'])
    EXPOSED = random.choice(['whois.donuts.co', 'whois.nic.exposed'])
    EXPRESS = random.choice(['whois.nic.express', 'whois.donuts.co'])
    EXTRASPACE = 'whois.afilias-srs.net'
    FAGE = 'whois.afilias-srs.net'
    FAIL = random.choice(['whois.nic.fail', 'whois.donuts.co'])
    FAIRWINDS = 'whois.nic.fairwinds'
    FAITH = 'whois.nic.faith'
    FAMILY = random.choice(['whois.nic.family', 'whois.rightside.co'])
    FAN = 'whois.nic.fan'
    FANS = 'whois.nic.fans'
    FARM = random.choice(['whois.donuts.co', 'whois.nic.farm'])
    FARMERS = None
    FASHION = random.choice(['whois.nic.fashion', 'whois-dub.mm-registry.com'])
    FAST = 'whois.nic.fast'
    FEDEX = random.choice(['whois.nic.fedex', 'whois.afilias-srs.net'])
    FEEDBACK = random.choice(['whois.centralnic.com', 'whois.nic.feedback'])
    FERRARI = random.choice(['whois.afilias-srs.net', 'whois.nic.ferrari'])
    FERRERO = None
    FIAT = 'whois.afilias-srs.net'
    FIDELITY = 'whois.nic.fidelity'
    FIDO = 'whois.afilias-srs.net'
    FILM = 'whois.nic.film'
    FINAL = 'whois.gtlds.nic.br'
    FINANCE = random.choice(['whois.nic.finance', 'whois.donuts.co'])
    FINANCIAL = random.choice(['whois.nic.financial', 'whois.donuts.co'])
    FIRE = 'whois.nic.fire'
    FIRESTONE = 'whois.nic.firestone'
    FIRMDALE = 'whois.nic.firmdale'
    FISH = random.choice(['whois.donuts.co', 'whois.nic.fish'])
    FISHING = random.choice(['whois.nic.fishing', 'whois-dub.mm-registry.com'])
    FIT = random.choice(['whois.nic.fit', 'whois-dub.mm-registry.com'])
    FITNESS = random.choice(['whois.nic.fitness', 'whois.donuts.co'])
    FLICKR = None
    FLIGHTS = random.choice(['whois.donuts.co', 'whois.nic.flights'])
    FLIR = None
    FLORIST = random.choice(['whois.nic.florist', 'whois.donuts.co'])
    FLOWERS = 'whois.uniregistry.net'
    FLSMIDTH = 'whois.ksregistry.net'
    FLY = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    FOO = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    FOOD = None
    FOODNETWORK = 'whois.nic.foodnetwork'
    FOOTBALL = random.choice(['whois.donuts.co', 'whois.nic.football'])
    FORD = None
    FOREX = 'whois.nic.forex'
    FORSALE = random.choice(['whois.nic.forsale', 'whois.unitedtld.com'])
    FORUM = 'whois.nic.forum'
    FOUNDATION = random.choice(['whois.nic.foundation', 'whois.donuts.co'])
    FOX = 'whois.nic.fox'
    FREE = 'whois.nic.free'
    FRESENIUS = random.choice(['whois.ksregistry.net', 'whois.nic.fresenius'])
    FRL = 'whois.nic.frl'
    FROGANS = random.choice(['whois-frogans.nic.fr', 'whois.nic.frogans'])
    FRONTDOOR = 'whois.nic.frontdoor'
    FRONTIER = None
    FTR = None
    FUJITSU = 'whois.nic.gmo'
    FUJIXEROX = 'whois.nic.fujixerox'
    FUN = 'whois.nic.fun'
    FUND = random.choice(['whois.nic.fund', 'whois.donuts.co'])
    FURNITURE = random.choice(['whois.nic.furniture', 'whois.donuts.co'])
    FUTBOL = random.choice(['whois.nic.futbol', 'whois.unitedtld.com'])
    FYI = random.choice(['whois.nic.fyi', 'whois.donuts.co'])
    GAL = random.choice(['whois.gal.coreregistry.net', 'whois.nic.gal'])
    GALLERY = random.choice(['whois.nic.gallery', 'whois.donuts.co'])
    GALLO = 'whois.nic.gallo'
    GALLUP = random.choice(['whois.afilias-srs.net', 'whois.nic.gallup'])
    GAME = 'whois.uniregistry.net'
    GAMES = random.choice(['whois.rightside.co', 'whois.nic.games'])
    GAP = None
    GARDEN = random.choice(['whois.nic.garden', 'whois-dub.mm-registry.com'])
    GAY = 'whois.nic.gay'
    GBIZ = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    GDN = 'whois.nic.gdn'
    GEA = random.choice(['whois.nic.gea', 'whois.afilias-srs.net'])
    GENT = 'whois.nic.gent'
    GENTING = 'whois.nic.genting'
    GEORGE = 'whois.nic.george'
    GGEE = 'whois.nic.ggee'
    GIFT = 'whois.uniregistry.net'
    GIFTS = random.choice(['whois.nic.gifts', 'whois.donuts.co'])
    GIVES = random.choice(['whois.rightside.co', 'whois.nic.gives'])
    GIVING = 'whois.nic.giving'
    GLADE = 'whois.nic.glade'
    GLASS = random.choice(['whois.donuts.co', 'whois.nic.glass'])
    GLE = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    GLOBAL = random.choice(['whois.nic.global', 'whois.afilias-srs.net'])
    GLOBO = 'whois.gtlds.nic.br'
    GMAIL = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    GMBH = random.choice(['whois.nic.gmbh', 'whois.donuts.co'])
    GMO = 'whois.nic.gmo'
    GMX = random.choice(['whois-fe1.gmx.tango.knipp.de', 'whois.nic.gmx'])
    GODADDY = 'whois.afilias-srs.net'
    GOLD = random.choice(['whois.nic.gold', 'whois.donuts.co'])
    GOLDPOINT = 'whois.nic.goldpoint'
    GOLF = random.choice(['whois.donuts.co', 'whois.nic.golf'])
    GOO = 'whois.nic.gmo'
    GOODHANDS = 'whois.afilias-srs.net'
    GOODYEAR = random.choice(['whois.nic.goodyear', 'whois.afilias-srs.net'])
    GOOG = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    GOOGLE = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    GOP = random.choice(['whois-cl01.mm-registry.com', 'whois.nic.gop'])
    GOT = 'whois.nic.got'
    GRAINGER = None
    GRAPHICS = random.choice(['whois.nic.graphics', 'whois.donuts.co'])
    GRATIS = random.choice(['whois.nic.gratis', 'whois.donuts.co'])
    GREEN = 'whois.afilias.net'
    GRIPE = random.choice(['whois.nic.gripe', 'whois.donuts.co'])
    GROUP = random.choice(['whois.donuts.co', 'whois.nic.group'])
    GUARDIAN = None
    GUCCI = None
    GUGE = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    GUIDE = random.choice(['whois.donuts.co', 'whois.nic.guide'])
    GUITARS = 'whois.uniregistry.net'
    GURU = random.choice(['whois.nic.guru', 'whois.donuts.co'])
    HAIR = 'whois.nic.hair'
    HAMBURG = 'whois.nic.hamburg'
    HANGOUT = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    HAUS = random.choice(['whois.nic.haus', 'whois.unitedtld.com'])
    HBO = None
    HDFC = random.choice(['whois.nic.hdfc', 'whois.afilias-srs.net'])
    HDFCBANK = random.choice(['whois.afilias-srs.net', 'whois.nic.hdfcbank'])
    HEALTH = None
    HEALTHCARE = random.choice(['whois.nic.healthcare', 'whois.donuts.co'])
    HELP = 'whois.uniregistry.net'
    HELSINKI = random.choice(['whois.nic.helsinki', 'whois.afilias-srs.net'])
    HERE = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    HERMES = 'whois.afilias-srs.net'
    HGTV = 'whois.nic.hgtv'
    HIPHOP = 'whois.uniregistry.net'
    HISAMITSU = 'whois.nic.gmo'
    HITACHI = 'whois.nic.gmo'
    HIV = random.choice(['whois.afilias-srs.net', 'whois.uniregistry.net'])
    HKT = random.choice(['whois.nic.hkt', 'whois.afilias-srs.net'])
    HOCKEY = random.choice(['whois.donuts.co', 'whois.nic.hockey'])
    HOLDINGS = random.choice(['whois.donuts.co', 'whois.nic.holdings'])
    HOLIDAY = random.choice(['whois.donuts.co', 'whois.nic.holiday'])
    HOMEDEPOT = random.choice(['whois.nic.homedepot', 'whois.afilias-srs.net'])
    HOMEGOODS = None
    HOMES = 'whois.afilias-srs.net'
    HOMESENSE = None
    HONDA = 'whois.nic.honda'
    HONEYWELL = None
    HORSE = random.choice(['whois.nic.horse', 'whois-dub.mm-registry.com'])
    HOSPITAL = 'whois.nic.hospital'
    HOST = random.choice(['whois.nic.host', 'whois.centralnic.com'])
    HOSTING = 'whois.uniregistry.net'
    HOT = 'whois.nic.hot'
    HOTELES = None
    HOTELS = None
    HOTMAIL = None
    HOUSE = random.choice(['whois.nic.house', 'whois.donuts.co'])
    HOW = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    HSBC = None
    HTC = None
    HUGHES = random.choice(['whois.afilias-srs.net', 'whois.nic.hughes'])
    HYATT = None
    HYUNDAI = 'whois.nic.hyundai'
    IBM = 'whois.nic.ibm'
    ICBC = random.choice(['whois.afilias-srs.net', 'whois.nic.icbc'])
    ICE = 'whois.nic.ice'
    ICU = 'whois.nic.icu'
    IEEE = None
    IFM = 'whois.nic.ifm'
    IINET ='whois.aridnrs.net.au'
    IKANO = random.choice(['whois.nic.ikano', 'whois.ikano.tld-box.at'])
    IMAMAT = 'whois.afilias-srs.net'
    IMDB = 'whois.nic.imdb'
    IMMO = random.choice(['whois.donuts.co', 'whois.nic.immo'])
    IMMOBILIEN = random.choice(['whois.nic.immobilien', 'whois.unitedtld.com'])
    INDUSTRIES = random.choice(['whois.donuts.co', 'whois.nic.industries'])
    INFINITI = 'whois.nic.gmo'
    INFO = random.choice(['whois.afilias.info', 'whois.afilias.net'])
    ING = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    INK = random.choice(['whois.centralnic.com', 'whois.nic.ink'])
    INSTITUTE = random.choice(['whois.donuts.co', 'whois.nic.institute'])
    INSURANCE = 'whois.nic.insurance'
    INSURE = random.choice(['whois.nic.insure', 'whois.donuts.co'])
    INTEL = None
    INTERNATIONAL = random.choice(['whois.donuts.co', 'whois.nic.international'])
    INTUIT = None
    INVESTMENTS = random.choice(['whois.donuts.co', 'whois.nic.investments'])
    IPIRANGA = None
    IRISH = random.choice(['whois.nic.irish', 'whois.afilias-srs.net'])
    ISELECT = 'whois.nic.iselect'
    ISMAILI = 'whois.afilias-srs.net'
    IST = 'whois.afilias-srs.net'
    ISTANBUL = 'whois.afilias-srs.net'
    ITAU = None
    ITV = 'whois.afilias-srs.net'
    IVECO = random.choice(['whois.afilias-srs.net', 'whois.nic.iveco'])
    IWC = None
    JAGUAR = 'whois.nic.jaguar'
    JAVA = 'whois.nic.java'
    JCB = 'whois.nic.gmo'
    JCP = 'whois.afilias-srs.net'
    JEEP = 'whois.afilias-srs.net'
    JETZT = 'whois.nic.jetzt'
    JEWELRY = random.choice(['whois.nic.jewelry', 'whois.donuts.co'])
    JIO = 'whois.nic.jio'
    JLC = None
    JLL = 'whois.afilias-srs.net'
    JMP = None
    JNJ = None
    JOBURG = 'joburg-whois.registry.net.za'
    JOT = 'whois.nic.jot'
    JOY = 'whois.nic.joy'
    JPMORGAN = None
    JPRS = None
    JUEGOS = 'whois.uniregistry.net'
    JUNIPER = 'whois.nic.juniper'
    KAUFEN = random.choice(['whois.nic.kaufen', 'whois.unitedtld.com'])
    KDDI = 'whois.nic.kddi'
    KERRYHOTELS = 'whois.nic.kerryhotels'
    KERRYLOGISTICS = 'whois.nic.kerrylogistics'
    KERRYPROPERTIES = 'whois.nic.kerryproperties'
    KFH = 'whois.nic.kfh'
    KIA = 'whois.nic.kia'
    KIM = 'whois.afilias.net'
    KINDER = None
    KINDLE = 'whois.nic.kindle'
    KITCHEN = random.choice(['whois.nic.kitchen', 'whois.donuts.co'])
    KIWI = random.choice(['whois.dot-kiwi.com', 'whois.nic.kiwi'])
    KOELN = random.choice(['whois.ryce-rsp.com', 'whois-fe1.pdt.koeln.tango.knipp.de'])
    KOMATSU = 'whois.nic.komatsu'
    KOSHER = random.choice(['whois.afilias-srs.net', 'whois.nic.kosher'])
    KPMG = None
    KPN = None
    KRD = random.choice(['whois.aridnrs.net.au', 'whois.nic.krd'])
    KRED = 'whois.nic.kred'
    KUOKGROUP = 'whois.nic.kuokgroup'
    KYOTO = 'whois.nic.kyoto'
    LACAIXA = 'whois.nic.lacaixa'
    LADBROKES = 'whois.nic.ladbrokes'
    LAMBORGHINI = 'whois.afilias-srs.net'
    LAMER = random.choice(['whois.afilias-srs.net', 'whois.nic.lamer'])
    LANCASTER = random.choice(['whois.nic.lancaster', 'whois-lancaster.nic.fr'])
    LANCIA = 'whois.afilias-srs.net'
    LANCOME = 'whois.nic.lancome'
    LAND = random.choice(['whois.nic.land', 'whois.donuts.co'])
    LANDROVER = 'whois.nic.landrover'
    LANXESS = None
    LASALLE = 'whois.afilias-srs.net'
    LAT = 'whois.nic.lat'
    LATINO = random.choice(['whois.nic.latino', 'whois.afilias-srs.net'])
    LATROBE = 'whois.nic.latrobe'
    LAW = random.choice(['whois.nic.law', 'whois-dub.mm-registry.com'])
    LAWYER = random.choice(['whois.rightside.co', 'whois.nic.lawyer'])
    LDS = random.choice(['whois.nic.lds', 'whois.afilias-srs.net'])
    LEASE = random.choice(['whois.donuts.co', 'whois.nic.lease'])
    LECLERC = 'whois-leclerc.nic.fr'
    LEFRAK = 'whois.nic.lefrak'
    LEGAL = random.choice(['whois.nic.legal', 'whois.donuts.co'])
    LEGO = 'whois.nic.lego'
    LEXUS = 'whois.nic.lexus'
    LGBT = 'whois.afilias.net'
    LIAISON = 'whois.nic.liaison'
    LIDL = 'whois.nic.lidl'
    LIFE = random.choice(['whois.donuts.co', 'whois.nic.life'])
    LIFEINSURANCE = None
    LIFESTYLE = 'whois.nic.lifestyle'
    LIGHTING = random.choice(['whois.donuts.co', 'whois.nic.lighting'])
    LIKE = 'whois.nic.like'
    LILLY = None
    LIMITED = random.choice(['whois.nic.limited', 'whois.donuts.co'])
    LIMO = random.choice(['whois.nic.limo', 'whois.donuts.co'])
    LINCOLN = None
    LINDE = 'whois.nic.linde'
    LINK = 'whois.uniregistry.net'
    LIPSY = 'whois.nic.lipsy'
    LIVE = random.choice(['whois.rightside.co', 'whois.nic.live'])
    LIVING = None
    LIXIL = 'whois.nic.lixil'
    LOAN = 'whois.nic.loan'
    LOANS = random.choice(['whois.donuts.co', 'whois.nic.loans'])
    LOCKER = random.choice(['whois.nic.locker', 'whois.afilias-srs.net'])
    LOCUS = 'whois.nic.locus'
    LOFT = None
    LOL = 'whois.uniregistry.net'
    LONDON = random.choice(['whois.nic.london', 'whois-lon.mm-registry.com'])
    LOTTE = 'whois.nic.lotte'
    LOTTO = 'whois.afilias.net'
    LOVE = random.choice(['whois.nic.love', 'whois.centralnic.com'])
    LPL = 'whois.nic.lpl'
    LPLFINANCIAL = 'whois.nic.lplfinancial'
    LTD = random.choice(['whois.nic.ltd', 'whois.donuts.co'])
    LTDA = 'whois.afilias-srs.net'
    LUNDBECK = 'whois.nic.lundbeck'
    LUPIN = None
    LUXE = random.choice(['whois.nic.luxe', 'whois-dub.mm-registry.com'])
    LUXURY = random.choice(['whois.nic.luxury', 'whois.donuts.co'])
    MACYS = 'whois.nic.macys'
    MADRID = random.choice(['whois.nic.madrid', 'whois.madrid.rs.corenic.net'])
    MAIF = None
    MAISON = random.choice(['whois.donuts.co', 'whois.nic.maison'])
    MAKEUP = 'whois.nic.makeup'
    MAN = 'whois.nic.man'
    MANAGEMENT = random.choice(['whois.donuts.co', 'whois.nic.management'])
    MANGO = random.choice(['whois.nic.mango', 'whois.mango.coreregistry.net'])
    MARKET = random.choice(['whois.rightside.co', 'whois.nic.market'])
    MARKETING = random.choice(['whois.nic.marketing', 'whois.donuts.co'])
    MARKETS = 'whois.nic.markets'
    MARRIOTT = 'whois.afilias-srs.net'
    MARSHALLS = None
    MASERATI = random.choice(['whois.nic.maserati', 'whois.afilias-srs.net'])
    MATTEL = None
    MBA = random.choice(['whois.nic.mba', 'whois.donuts.co'])
    MCD = None
    MCDONALDS = None
    MCKINSEY = random.choice(['whois.nic.mckinsey', 'whois.afilias-srs.net'])
    MED = 'whois.nic.med'
    MEDIA = random.choice(['whois.donuts.co', 'whois.nic.media'])
    MEET = random.choice(['whois.nic.google', 'whois.afilias.net'])
    MELBOURNE = random.choice(['whois.aridnrs.net.au', 'whois.nic.melbourne'])
    MEME = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    MEMORIAL = random.choice(['whois.donuts.co', 'whois.nic.memorial'])
    MEN = 'whois.nic.men'
    MENU = 'whois.nic.menu'
    MEO = None
    METLIFE = 'whois.afilias-srs.net'
    MIAMI = random.choice(['whois.nic.miami', 'whois-dub.mm-registry.com'])
    MICROSOFT = None
    MINI = random.choice(['whois.ksregistry.net', 'whois.nic.mini'])
    MINT = None
    MIT = 'whois.afilias-srs.net'
    MITSUBISHI = 'whois.nic.gmo'
    MLB = None
    MLS = 'whois.nic.mls'
    MMA = random.choice(['whois-mma.nic.fr', 'whois.nic.mma'])
    MOBILE = 'whois.nic.mobile'
    MOBILY = None
    MODA = random.choice(['whois.unitedtld.com', 'whois.nic.moda'])
    MOE = 'whois.nic.moe'
    MOI = 'whois.nic.moi'
    MOM = 'whois.uniregistry.net'
    MONASH = 'whois.nic.monash'
    MONEY = random.choice(['whois.nic.money', 'whois.donuts.co'])
    MONSTER = random.choice(['whois.afilias-srs.net', 'whois.nic.monster'])
    MONTBLANC = None
    MOPAR = 'whois.afilias-srs.net'
    MORMON = random.choice(['whois.nic.mormon', 'whois.afilias-srs.net'])
    MORTGAGE = random.choice(['whois.nic.mortgage', 'whois.rightside.co'])
    MOSCOW = 'whois.nic.moscow'
    MOTO = None
    MOTORCYCLES = 'whois.afilias-srs.net'
    MOV = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    MOVIE = random.choice(['whois.donuts.co', 'whois.nic.movie'])
    MOVISTAR = 'whois-fe.movistar.tango.knipp.de'
    MSD = None
    MTN = 'whois.nic.mtn'
    MTPC = 'whois.nic.gmo'
    MTR = 'whois.nic.mtr'
    MUTUAL = None
    MUTUELLE = 'whois-mutuelle.nic.fr'
    NAB = 'whois.nic.nab'
    NADEX = 'whois.nic.nadex'
    NAGOYA = random.choice(['whois.gmoregistry.net', 'whois.nic.nagoya'])
    NAME = 'whois.nic.name'
    NATIONWIDE = 'whois.nic.nationwide'
    NATURA = random.choice(['whois.gtlds.nic.br', 'whois.afilias-srs.net'])
    NAVY = random.choice(['whois.rightside.co', 'whois.nic.navy'])
    NBA = None
    NEC = 'whois.nic.nec'
    NET = random.choice(['whois.verisign-grs.com', 'whois.crsnic.net'])
    NETBANK = 'whois.nic.netbank'
    NETFLIX = None
    NETWORK = random.choice(['whois.nic.network', 'whois.donuts.co'])
    NEUSTAR = None
    NEW = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    NEWHOLLAND = 'whois.afilias-srs.net'
    NEWS = random.choice(['whois.nic.news', 'whois.rightside.co'])
    NEXT = 'whois.nic.next'
    NEXTDIRECT = 'whois.nic.nextdirect'
    NEXUS = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    NFL = None
    NGO = 'whois.publicinterestregistry.net'
    NHK = 'whois.nic.nhk'
    NICO = 'whois.nic.nico'
    NIKE = None
    NIKON = 'whois.nic.nikon'
    NINJA = random.choice(['whois.nic.ninja', 'whois.donuts.co'])
    NISSAN = 'whois.nic.gmo'
    NISSAY = 'whois.nic.nissay'
    NOKIA = 'whois.afilias-srs.net'
    NORTHWESTERNMUTUAL = None
    NORTON = 'whois.nic.norton'
    NOW = 'whois.nic.now'
    NOWRUZ = random.choice(['whois.agitsys.net', 'whois.nic.nowruz'])
    NOWTV = random.choice(['whois.nic.nowtv', 'whois.afilias-srs.net'])
    NRA = 'whois.afilias-srs.net'
    NRW = 'whois.nic.nrw'
    NTT = None
    NYC = 'whois.nic.nyc'
    OBI = 'whois.nic.obi'
    OBSERVER = 'whois.nic.observer'
    OFF = 'whois.nic.off'
    OFFICE = None
    OKINAWA = 'whois.nic.okinawa'
    OLAYAN = 'whois.nic.olayan'
    OLAYANGROUP = 'whois.nic.olayangroup'
    OLDNAVY = None
    OLLO = random.choice(['whois.nic.ollo', 'whois.afilias-srs.net'])
    OMEGA = 'whois.nic.omega'
    ONE = 'whois.nic.one'
    ONG = 'whois.publicinterestregistry.net'
    ONL = 'whois.afilias-srs.net'
    ONLINE = random.choice(['whois.nic.online', 'whois.centralnic.com'])
    ONYOURSIDE = 'whois.nic.onyourside'
    OOO = 'whois.nic.ooo'
    OPEN = None
    ORACLE = 'whois.nic.oracle'
    ORANGE = 'whois.nic.orange'
    ORG = 'whois.pir.org'
    ORGANIC = random.choice(['whois.afilias.net', 'whois.afilias-srs.net'])
    ORIENTEXPRESS ='whois.afilias-srs.net'
    ORIGINS = random.choice(['whois.afilias-srs.net', 'whois.nic.origins'])
    OSAKA = 'whois.nic.osaka'
    OTSUKA = 'whois.nic.otsuka'
    OTT = random.choice(['whois.nic.ott', 'whois.afilias-srs.net'])
    OVH = 'whois-ovh.nic.fr'
    PAGE = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    PAMPEREDCHEF = None
    PANASONIC = 'whois.nic.gmo'
    PANERAI = None
    PARIS = 'whois-paris.nic.fr'
    PARS = random.choice(['whois.agitsys.net', 'whois.nic.pars'])
    PARTNERS = random.choice(['whois.donuts.co', 'whois.nic.partners'])
    PARTS = random.choice(['whois.donuts.co', 'whois.nic.parts'])
    PARTY = 'whois.nic.party'
    PASSAGENS = None
    PAY = 'whois.nic.pay'
    PCCW = random.choice(['whois.nic.pccw', 'whois.afilias-srs.net'])
    PET = 'whois.afilias.net'
    PFIZER = None
    PHARMACY = 'whois.nic.pharmacy'
    PHILIPS = 'whois.nic.philips'
    PHONE = 'whois.nic.phone'
    PHOTO = 'whois.uniregistry.net'
    PHOTOGRAPHY = random.choice(['whois.donuts.co', 'whois.nic.photography'])
    PHOTOS = random.choice(['whois.nic.photos', 'whois.donuts.co'])
    PHYSIO = 'whois.nic.physio'
    PIAGET = None
    PICS = 'whois.uniregistry.net'
    PICTET = None
    PICTURES = random.choice(['whois.donuts.co', 'whois.nic.pictures'])
    PID = 'whois.nic.pid'
    PIN = 'whois.nic.pin'
    PING = None
    PINK = 'whois.afilias.net'
    PIONEER = 'whois.nic.gmo'
    PIZZA = random.choice(['whois.nic.pizza', 'whois.donuts.co'])
    PLACE = random.choice(['whois.donuts.co', 'whois.nic.place'])
    PLAY = 'whois.nic.google'
    PLAYSTATION = 'whois.nic.playstation'
    PLUMBING = random.choice(['whois.donuts.co', 'whois.nic.plumbing'])
    PLUS = random.choice(['whois.nic.plus', 'whois.donuts.co'])
    PNC = random.choice(['whois.nic.pnc', 'whois.afilias-srs.net'])
    POHL = random.choice(['whois.ksregistry.net', 'whois.nic.pohl'])
    POKER = 'whois.afilias.net'
    POLITIE = 'whois.nic.politie'
    PORN = random.choice(['whois.registrar.adult', 'whois.afilias-srs.net'])
    PRAMERICA = None
    PRAXI = None
    PRESS = random.choice(['whois.nic.press', 'whois.centralnic.com'])
    PRIME = 'whois.nic.prime'
    PRO = 'whois.afilias.net'
    PROD = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    PRODUCTIONS = random.choice(['whois.nic.productions', 'whois.donuts.co'])
    PROF = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    PROGRESSIVE = 'whois.afilias-srs.net'
    PROMO = 'whois.afilias.net'
    PROPERTIES = random.choice(['whois.donuts.co', 'whois.nic.properties'])
    PROPERTY = 'whois.uniregistry.net'
    PROTECTION = random.choice(['whois.nic.protection', 'whois.centralnic.com'])
    PRU = None
    PRUDENTIAL = None
    PUB = random.choice(['whois.nic.pub', 'whois.unitedtld.com'])
    PWC = 'whois.afilias-srs.net'
    QPON = 'whois.nic.qpon'
    QUEBEC = 'whois.nic.quebec'
    QUEST = 'whois.nic.quest'
    QVC = None
    RACING = 'whois.nic.racing'
    RADIO = 'whois.nic.radio'
    RAID = 'whois.nic.raid'
    READ = 'whois.nic.read'
    REALESTATE = 'whois.nic.realestate'
    REALTOR = None
    REALTY = 'whois.nic.realty'
    RECIPES = random.choice(['whois.nic.recipes', 'whois.donuts.co'])
    RED = 'whois.afilias.net'
    REDSTONE = random.choice(['whois.afilias-srs.net', 'whois.nic.redstone'])
    REDUMBRELLA = 'whois.afilias-srs.net'
    REHAB = random.choice(['whois.rightside.co', 'whois.nic.rehab'])
    REISE = 'whois.nic.reise'
    REISEN = random.choice(['whois.donuts.co', 'whois.nic.reisen'])
    REIT = 'whois.nic.reit'
    RELIANCE = 'whois.nic.reliance'
    REN = 'whois.nic.ren'
    RENT = 'whois.nic.rent'
    RENTALS = random.choice(['whois.nic.rentals', 'whois.donuts.co'])
    REPAIR = random.choice(['whois.donuts.co', 'whois.nic.repair'])
    REPORT = random.choice(['whois.donuts.co', 'whois.nic.report'])
    REPUBLICAN = random.choice(['whois.rightside.co', 'whois.nic.republican'])
    REST = random.choice(['whois.nic.rest', 'whois.centralnic.com'])
    RESTAURANT = random.choice(['whois.nic.restaurant', 'whois.donuts.co'])
    REVIEW = 'whois.nic.review'
    REVIEWS = random.choice(['whois.unitedtld.com', 'whois.nic.reviews'])
    REXROTH = 'whois.nic.rexroth'
    RICH = 'whois.afilias-srs.net'
    RICHARDLI = random.choice(['whois.nic.richardli', 'whois.afilias-srs.net'])
    RICOH = 'whois.nic.ricoh'
    RIGHTATHOME = 'whois.nic.rightathome'
    RIL = 'whois.nic.ril'
    RIO = 'whois.gtlds.nic.br'
    RIP = random.choice(['whois.nic.rip', 'whois.rightside.co'])
    RMIT = 'whois.nic.rmit'
    ROCHER = None
    ROCKS = random.choice(['whois.unitedtld.com', 'whois.nic.rocks'])
    RODEO = random.choice(['whois.nic.rodeo', 'whois-dub.mm-registry.com'])
    ROGERS = 'whois.afilias-srs.net'
    ROOM = 'whois.nic.room'
    RSVP = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    RUGBY = 'whois.nic.rugby'
    RUHR = 'whois.nic.ruhr'
    RUN = random.choice(['whois.donuts.co', 'whois.nic.run'])
    RWE = 'whois.nic.rwe'
    RYUKYU = 'whois.nic.ryukyu'
    SAARLAND = random.choice(['whois.ksregistry.net', 'whois.nic.saarland'])
    SAFE = 'whois.nic.safe'
    SAFETY = None
    SAKURA = None
    SALE = random.choice(['whois.nic.sale', 'whois.rightside.co'])
    SALON = random.choice(['whois.donuts.co', 'whois.nic.salon'])
    SAMSCLUB = 'whois.nic.samsclub'
    SAMSUNG = 'whois.nic.samsung'
    SANDVIK = 'whois.nic.sandvik'
    SANDVIKCOROMANT = 'whois.nic.sandvikcoromant'
    SANOFI = 'whois.nic.sanofi'
    SAP = 'whois.nic.sap'
    SAPO = None
    SARL = random.choice(['whois.nic.sarl', 'whois.donuts.co'])
    SAS = None
    SAVE = 'whois.nic.save'
    SAXO = random.choice(['whois.aridnrs.net.au', 'whois.nic.saxo'])
    SBI = random.choice(['whois.afilias-srs.net', 'whois.nic.sbi'])
    SBS = 'whois.nic.sbs'
    SCA = 'whois.nic.sca'
    SCB = 'whois.nic.scb'
    SCHAEFFLER = 'whois.afilias-srs.net'
    SCHMIDT = 'whois.nic.schmidt'
    SCHOLARSHIPS = random.choice(['whois.nic.scholarships', 'whois.afilias-srs.net'])
    SCHOOL = random.choice(['whois.donuts.co', 'whois.nic.school'])
    SCHULE = random.choice(['whois.nic.schule', 'whois.donuts.co'])
    SCHWARZ = 'whois.nic.schwarz'
    SCIENCE = 'whois.nic.science'
    SCJOHNSON = 'whois.nic.scjohnson'
    SCOR = 'whois.nic.scor'
    SCOT = random.choice(['whois.nic.scot', 'whois.scot.coreregistry.net'])
    SEAT = 'whois.nic.seat'
    SECURE = 'whois.nic.secure'
    SECURITY = 'whois.nic.security'
    SEEK = 'whois.nic.seek'
    SELECT = 'whois.nic.select'
    SENER = None
    SERVICES = random.choice(['whois.donuts.co', 'whois.nic.services'])
    SES = 'whois.nic.ses'
    SEVEN = 'whois.nic.seven'
    SEW = 'whois.afilias-srs.net'
    SEX = random.choice(['whois.registrar.adult', 'whois.afilias-srs.net'])
    SEXY = 'whois.uniregistry.net'
    SFR = 'whois.nic.sfr'
    SHANGRILA = 'whois.nic.shangrila'
    SHARP = 'whois.nic.gmo'
    SHAW = 'whois.afilias-srs.net'
    SHELL = 'whois.nic.shell'
    SHIA = random.choice(['whois.agitsys.net', 'whois.nic.shia'])
    SHIKSHA = 'whois.afilias.net'
    SHOES = random.choice(['whois.nic.shoes', 'whois.donuts.co'])
    SHOP = 'whois.nic.shop'
    SHOPPING = random.choice(['whois.donuts.co', 'whois.nic.shopping'])
    SHOUJI = 'whois.teleinfo.cn'
    SHOW = random.choice(['whois.donuts.co', 'whois.nic.show'])
    SHOWTIME = 'whois.afilias-srs.net'
    SHRIRAM = 'whois.afilias-srs.net'
    SILK = 'whois.nic.silk'
    SINA = random.choice(['whois.nic.sina', 'whois.afilias-srs.net'])
    SINGLES = random.choice(['whois.donuts.co', 'whois.nic.singles'])
    SITE = random.choice(['whois.nic.site', 'whois.centralnic.com'])
    SKI = random.choice(['whois.ksregistry.net', 'whois.afilias.net'])
    SKIN = 'whois.nic.skin'
    SKY = 'whois.nic.sky'
    SKYPE = None
    SLING = random.choice(['whois.afilias-srs.net', 'whois.nic.sling'])
    SMART = random.choice(['whois-gtld.smart.com.ph', 'whois.nic.smart'])
    SMILE = 'whois.nic.smile'
    SNCF = random.choice(['whois-sncf.nic.fr', 'whois.nic.sncf'])
    SOCCER = random.choice(['whois.nic.soccer', 'whois.donuts.co'])
    SOCIAL = random.choice(['whois.nic.social', 'whois.unitedtld.com'])
    SOFTBANK = 'whois.nic.softbank'
    SOFTWARE = random.choice(['whois.rightside.co', 'whois.nic.software'])
    SOHU = 'whois.gtld.knet.cn'
    SOLAR = random.choice(['whois.nic.solar', 'whois.donuts.co'])
    SOLUTIONS = random.choice(['whois.nic.solutions', 'whois.donuts.co'])
    SONG = None
    SONY = 'whois.nic.sony'
    SOY = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    SPACE = 'whois.nic.space'
    SPIEGEL = 'whois.ksregistry.net'
    SPOT = 'whois.nic.spot'
    SPREADBETTING = 'whois.nic.spreadbetting'
    SRL = 'whois.afilias-srs.net'
    SRT = 'whois.afilias-srs.net'
    STADA = 'whois.afilias-srs.net'
    STAPLES = None
    STAR = random.choice(['whois.nic.star', 'whois.afilias-srs.net'])
    STARHUB = 'whois.nic.starhub'
    STATEBANK = random.choice(['whois.afilias-srs.net', 'whois.nic.statebank'])
    STATEFARM = None
    STATOIL = 'whois.nic.statoil'
    STC = random.choice(['whois.nic.stc', 'whois.centralnic.com'])
    STCGROUP = random.choice(['whois.nic.stcgroup', 'whois.centralnic.com'])
    STOCKHOLM = 'whois.afilias-srs.net'
    STORAGE = random.choice(['whois.afilias-srs.net', 'whois.nic.storage'])
    STORE = 'whois.nic.store'
    STREAM = 'whois.nic.stream'
    STUDIO = random.choice(['whois.rightside.co', 'whois.nic.studio'])
    STUDY = 'whois.nic.study'
    STYLE = random.choice(['whois.nic.style', 'whois.donuts.co'])
    SUCKS = 'whois.nic.sucks'
    SUPPLIES = random.choice(['whois.nic.supplies', 'whois.donuts.co'])
    SUPPLY = random.choice(['whois.donuts.co', 'whois.nic.supply'])
    SUPPORT = random.choice(['whois.donuts.co', 'whois.nic.support'])
    SURF = random.choice(['whois.nic.surf', 'whois-dub.mm-registry.com'])
    SURGERY = random.choice(['whois.donuts.co', 'whois.nic.surgery'])
    SUZUKI = 'whois.nic.suzuki'
    SWATCH = 'whois.nic.swatch'
    SWIFTCOVER = None
    SWISS = 'whois.nic.swiss'
    SYDNEY = 'whois.nic.sydney'
    SYMANTEC = 'whois.nic.symantec'
    SYSTEMS = random.choice(['whois.donuts.co', 'whois.nic.systems'])
    TAB = 'whois.nic.tab'
    TAIPEI = 'whois.nic.taipei'
    TALK = 'whois.nic.talk'
    TAOBAO = None
    TARGET = None
    TATAMOTORS = 'whois.nic.tatamotors'
    TATAR = 'whois.nic.tatar'
    TATTOO = 'whois.uniregistry.net'
    TAX = random.choice(['whois.donuts.co', 'whois.nic.tax'])
    TAXI = random.choice(['whois.donuts.co', 'whois.nic.taxi'])
    TCI = random.choice(['whois.agitsys.net', 'whois.nic.tci'])
    TDK = 'whois.nic.tdk'
    TEAM = random.choice(['whois.donuts.co', 'whois.nic.team'])
    TECH = 'whois.nic.tech'
    TECHNOLOGY = random.choice(['whois.nic.technology', 'whois.donuts.co'])
    TELECITY = 'whois.nic.telecity'
    TELEFONICA = 'whois-fe.telefonica.tango.knipp.de'
    TEMASEK = 'whois.afilias-srs.net'
    TENNIS = random.choice(['whois.nic.tennis', 'whois.donuts.co'])
    TEVA = 'whois.nic.teva'
    THD = random.choice(['whois.afilias-srs.net', 'whois.nic.thd'])
    THEATER = random.choice(['whois.nic.theater', 'whois.donuts.co'])
    THEATRE = 'whois.nic.theatre'
    TIAA = 'whois.nic.tiaa'
    TICKETS = 'whois.nic.tickets'
    TIENDA = random.choice(['whois.nic.tienda', 'whois.donuts.co'])
    TIFFANY = 'whois.nic.tiffany'
    TIPS = random.choice(['whois.nic.tips', 'whois.donuts.co'])
    TIRES = random.choice(['whois.donuts.co', 'whois.nic.tires'])
    TIROL = 'whois.nic.tirol'
    TJMAXX = None
    TJX = None
    TKMAXX = None
    TMALL = None
    TODAY = random.choice(['whois.donuts.co', 'whois.nic.today'])
    TOKYO = 'whois.nic.tokyo'
    TOOLS = random.choice(['whois.donuts.co', 'whois.nic.tools'])
    TOP = 'whois.nic.top'
    TORAY = 'whois.nic.toray'
    TOSHIBA = 'whois.nic.toshiba'
    TOTAL = random.choice(['whois.nic.total', 'whois-total.nic.fr'])
    TOURS = random.choice(['whois.nic.tours', 'whois.donuts.co'])
    TOWN = random.choice(['whois.donuts.co', 'whois.nic.town'])
    TOYOTA = 'whois.nic.toyota'
    TOYS = random.choice(['whois.nic.toys', 'whois.donuts.co'])
    TRADE = 'whois.nic.trade'
    TRADING = 'whois.nic.trading'
    TRAINING = random.choice(['whois.donuts.co', 'whois.nic.training'])
    TRAVELCHANNEL = 'whois.nic.travelchannel'
    TRAVELERS = 'whois.afilias-srs.net'
    TRAVELERSINSURANCE = 'whois.afilias-srs.net'
    TRUST = 'whois.nic.trust'
    TRV = 'whois.afilias-srs.net'
    TUBE = None
    TUI = random.choice(['whois.ksregistry.net', 'whois.nic.tui'])
    TUNES = 'whois.nic.tunes'
    TUSHU = 'whois.nic.tushu'
    TVS = random.choice(['whois.nic.tvs', 'whois.afilias-srs.net'])
    UBANK = 'whois.nic.ubank'
    UBS = 'whois.nic.ubs'
    UCONNECT = 'whois.afilias-srs.net'
    UNICOM = 'whois.nic.unicom'
    UNIVERSITY = random.choice(['whois.nic.university', 'whois.donuts.co'])
    UNO = 'whois.nic.uno'
    UOL = 'whois.gtlds.nic.br'
    UPS = random.choice(['whois.nic.ups', 'whois.afilias-srs.net'])
    VACATIONS = random.choice(['whois.nic.vacations', 'whois.donuts.co'])
    VANA = 'whois.nic.vana'
    VANGUARD = 'whois.nic.vanguard'
    VEGAS = 'whois.afilias-srs.net'
    VENTURES = random.choice(['whois.nic.ventures', 'whois.donuts.co'])
    VERISIGN = 'whois.nic.verisign'
    VERSICHERUNG = 'whois.nic.versicherung'
    VET = random.choice(['whois.nic.vet', 'whois.rightside.co'])
    VIAJES = random.choice(['whois.nic.viajes', 'whois.donuts.co'])
    VIDEO = random.choice(['whois.rightside.co', 'whois.nic.video'])
    VIG = 'whois.afilias-srs.net'
    VIKING = 'whois.afilias-srs.net'
    VILLAS = random.choice(['whois.nic.villas', 'whois.donuts.co'])
    VIN = random.choice(['whois.nic.vin', 'whois.donuts.co'])
    VIP = random.choice(['whois.nic.vip', 'whois-dub.mm-registry.com'])
    VIRGIN = 'whois.nic.virgin'
    VISA = 'whois.nic.visa'
    VISION = random.choice(['whois.nic.vision', 'whois.donuts.co'])
    VISTA = 'whois.nic.vista'
    VISTAPRINT = 'whois.nic.vistaprint'
    VIVA = random.choice(['whois.nic.viva', 'whois.centralnic.com'])
    VIVO = None
    VLAANDEREN = 'whois.nic.vlaanderen'
    VODKA = random.choice(['whois.nic.vodka', 'whois-dub.mm-registry.com'])
    VOLKSWAGEN = 'whois.afilias-srs.net'
    VOLVO = 'whois.nic.volvo'
    VOTE = 'whois.afilias.net'
    VOTING = random.choice(['whois.nic.voting', 'whois.voting.tld-box.at'])
    VOTO = 'whois.afilias.net'
    VOYAGE = random.choice(['whois.donuts.co', 'whois.nic.voyage'])
    VUELOS = None
    WALES = 'whois.nic.wales'
    WALMART = 'whois.nic.walmart'
    WALTER = 'whois.nic.walter'
    WANG = 'whois.gtld.knet.cn'
    WANGGOU = 'whois.nic.wanggou'
    WARMAN = 'whois.nic.warman'
    WATCH = random.choice(['whois.donuts.co', 'whois.nic.watch'])
    WATCHES = 'whois.nic.watches'
    WEATHER = None
    WEATHERCHANNEL = None
    WEBCAM = 'whois.nic.webcam'
    WEBER = 'whois.nic.weber'
    WEBSITE = 'whois.nic.website'
    WED = 'whois.nic.wed'
    WEDDING = random.choice(['whois.nic.wedding', 'whois-dub.mm-registry.com'])
    WEIBO = random.choice(['whois.nic.weibo', 'whois.afilias-srs.net'])
    WEIR = None
    WHOSWHO = 'whois.nic.whoswho'
    WIEN = 'whois.nic.wien'
    WIKI = 'whois.nic.wiki'
    WILLIAMHILL = None
    WIN = 'whois.nic.win'
    WINDOWS = None
    WINE = random.choice(['whois.nic.wine', 'whois.donuts.co'])
    WINNERS = None
    WME = random.choice(['whois.nic.wme', 'whois.centralnic.com'])
    WOLTERSKLUWER = random.choice(['whois.nic.wolterskluwer', 'whois.afilias-srs.net'])
    WOODSIDE = 'whois.nic.woodside'
    WORK = random.choice(['whois.nic.work', 'whois-dub.mm-registry.com'])
    WORKS = random.choice(['whois.nic.works', 'whois.donuts.co'])
    WORLD = random.choice(['whois.nic.world', 'whois.donuts.co'])
    WOW = 'whois.nic.wow'
    WTC = 'whois.nic.wtc'
    WTF = random.choice(['whois.donuts.co', 'whois.nic.wtf'])
    XBOX = None
    XEROX = 'whois.nic.xerox'
    XFINITY = 'whois.nic.xfinity'
    XIHUAN = 'whois.teleinfo.cn'
    XIN = random.choice(['whois.afilias-srs.net', 'whois.nic.xin'])
    XN__11B4C3D = 'whois.nic.xn--11b4c3d'
    XN__1CK2E1B = None
    XN__1QQW23A = 'whois.ngtld.cn'
    XN__30RR7Y = 'whois.gtld.knet.cn'
    XN__3BST00M = 'whois.gtld.knet.cn'
    XN__3DS443G = 'whois.teleinfo.cn'
    XN__3OQ18VL8PN36A = 'whois.nic.xn--3oq18vl8pn36a'
    XN__3PXU8K = 'whois.nic.xn--3pxu8k'
    XN__42C2D9A = 'whois.nic.xn--42c2d9a'
    XN__45Q11C = 'whois.nic.xn--45q11c'
    XN__4GBRIM = 'whois.afilias-srs.net'
    XN__55QW42G = 'whois.conac.cn'
    XN__55QX5D = 'whois.ngtld.cn'
    XN__5SU34J936BGSG = 'whois.nic.xn--5su34j936bgsg'
    XN__5TZM5G = 'whois.nic.xn--5tzm5g'
    XN__6FRZ82G = 'whois.afilias.net'
    XN__6QQ986B3XL = 'whois.gtld.knet.cn'
    XN__80ADXHKS = 'whois.nic.xn--80adxhks'
    XN__80AQECDR1A = 'whois.nic.xn--80aqecdr1a'
    XN__80ASEHDB = 'whois.nic.xn--80asehdb'
    XN__80ASWG = 'whois.nic.xn--80aswg'
    XN__8Y0A063A = 'whois.nic.xn--8y0a063a'
    XN__9DBQ2A = 'whois.nic.xn--9dbq2a'
    XN__9ET52U = 'whois.gtld.knet.cn'
    XN__9KRT00A = 'whois.nic.xn--9krt00a'
    XN__B4W605FERD = 'whois.afilias-srs.net'
    XN__BCK1B9A5DRE4C = None
    XN__C1AVG = 'whois.publicinterestregistry.net'
    XN__C2BR7G = 'whois.nic.xn--c2br7g'
    XN__CCK2B3B = None
    XN__CG4BKI = 'whois.kr'
    XN__CZR694B = None
    XN__CZRS0T = 'whois.nic.xn--czrs0t'
    XN__CZRU2D = 'whois.gtld.knet.cn'
    XN__D1ACJ3B = 'whois.nic.xn--d1acj3b'
    XN__ECKVDTC9D = None
    XN__EFVY88H = 'whois.nic.xn--efvy88h'
    XN__ESTV75G = None
    XN__FCT429K = None
    XN__FHBEI = 'whois.nic.xn--fhbei'
    XN__FIQ228C5HS = 'whois.teleinfo.cn'
    XN__FIQ64B = 'whois.gtld.knet.cn'
    XN__FJQ720A = 'whois.nic.xn--fjq720a'
    XN__FLW351E = 'whois.nic.google'
    XN__FZYS8D69UVGM = 'whois.nic.xn--fzys8d69uvgm'
    XN__G2XX48C = None
    XN__GCKR3F0F = None
    XN__GK3AT1E = None
    XN__HXT814E = 'whois.nic.xn--hxt814e'
    XN__I1B6B1A6A2E = 'whois.publicinterestregistry.net'
    XN__IMR513N = None
    XN__IO0A7I = 'whois.ngtld.cn'
    XN__J1AEF = 'whois.nic.xn--j1aef'
    XN__JLQ61U9W7B = 'whois.nic.xn--jlq61u9w7b'
    XN__JVR189M = None
    XN__KCRX77D1X4A = 'whois.nic.xn--kcrx77d1x4a'
    XN__KPU716F = None
    XN__KPUT3I = 'whois.nic.xn--kput3i'
    XN__MGBA3A3EJT = None
    XN__MGBA7C0BBN0A = 'whois.nic.xn--mgba7c0bbn0a'
    XN__MGBAB2BD = 'whois.nic.xn--mgbab2bd'
    XN__MGBB9FBPOB = None
    XN__MGBCA7DZDO = 'whois.nic.xn--mgbca7dzdo'
    XN__MGBI4ECEXP = 'whois.nic.xn--mgbi4ecexp'
    XN__MGBT3DHD = 'whois.nic.xn--mgbt3dhd'
    XN__MK1BU44C = 'whois.nic.xn--mk1bu44c'
    XN__MXTQ1M = 'whois.nic.xn--mxtq1m'
    XN__NGBC5AZD = 'whois.nic.xn--ngbc5azd'
    XN__NGBE9E0A = 'whois.nic.xn--ngbe9e0a'
    XN__NQV7F = 'whois.publicinterestregistry.net'
    XN__NQV7FS00EMA = 'whois.nic.xn--nqv7fs00ema'
    XN__NYQY26A = None
    XN__P1ACF = 'whois.nic.xn--p1acf'
    XN__PBT977C = None
    XN__PSSY2U = 'whois.nic.xn--pssy2u'
    XN__Q9JYB4C = 'whois.nic.google'
    XN__QCKA1PMC = 'whois.nic.google'
    XN__RHQV96G = None
    XN__ROVU88B = None
    XN__SES554G = 'whois.nic.xn--ses554g'
    XN__T60B56A = 'whois.nic.xn--t60b56a'
    XN__TCKWE = 'whois.nic.xn--tckwe'
    XN__TIQ49XQYJ = 'whois.nic.xn--tiq49xqyj'
    XN__UNUP4Y = 'whois.nic.xn--unup4y'
    XN__VERMGENSBERATER__CTB = 'whois.nic.xn--vermgensberater-ctb'
    XN__VERMGENSBERATUNG__PWB = 'whois.nic.xn--vermgensberatung-pwb'
    XN__VHQUV = 'whois.nic.xn--vhquv'
    XN__VUQ861B = 'whois.teleinfo.cn'
    XN__W4R85EL8FHU5DNRA = 'whois.nic.xn--w4r85el8fhu5dnra'
    XN__W4RS40L = 'whois.nic.xn--w4rs40l'
    XN__XHQ521B = 'whois.ngtld.cn'
    XN__ZFR164B = 'whois.conac.cn'
    XPERIA = 'whois.nic.xperia'
    XYZ = 'whois.nic.xyz'
    YACHTS = 'whois.afilias-srs.net'
    YAHOO = None
    YAMAXUN = 'whois.nic.yamaxun'
    YANDEX = None
    YODOBASHI = 'whois.nic.gmo'
    YOGA = random.choice(['whois.nic.yoga', 'whois-dub.mm-registry.com'])
    YOKOHAMA = 'whois.nic.yokohama'
    YOU = 'whois.nic.you'
    YOUTUBE = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    YUN = 'whois.teleinfo.cn'
    ZAPPOS = 'whois.nic.zappos'
    ZARA = 'whois.afilias-srs.net'
    ZERO = None
    ZIP = random.choice(['whois.nic.google', 'domain-registry-whois.l.google.com'])
    ZIPPO = None
    ZONE = random.choice(['whois.nic.zone', 'whois.donuts.co'])
    ZUERICH = random.choice(['whois.ksregistry.net', 'whois.nic.zuerich'])
